In [3]:
from process_data import DataProcessor
import pandas as pd

In [2]:
folder = 'data/'
data_files = ['normal_data.csv', 'fault_data.csv']

In [4]:
dfs = []

for file in data_files:
    directory = folder + file
    dfs.append(pd.read_csv(directory))

In [10]:
dfs[0]['X100_FE_time']

0         0.192922
1         0.164364
2         0.090811
3         0.086496
4         0.099235
            ...
485638    0.125122
485639    0.124916
485640    0.109302
485641    0.052185
485642   -0.004520
Name: X100_FE_time, Length: 485643, dtype: float64

In [7]:
dfs[1]

,X188_DE_time,X188_FE_time,X188_BA_time,fault_diameter,horse_power,rounds_per_minute,fault_end,samples_per_second
0,0.105420,0.204633,0.049371,14,3,1730,drive_end,12000
1,-0.107370,0.248395,0.062489,14,3,1730,drive_end,12000
2,-0.163410,0.042324,0.044664,14,3,1730,drive_end,12000
3,0.118903,-0.015615,0.067921,14,3,1730,drive_end,12000
4,0.184039,-0.058555,0.054361,14,3,1730,drive_end,12000
...,...,...,...,...,...,...,...,...
122131,0.895667,0.212851,0.150609,14,3,1730,drive_end,12000
122132,0.273053,-0.010684,0.149200,14,3,1730,drive_end,12000
122133,-0.582168,0.015820,0.079066,14,3,1730,drive_end,12000
122134,0.074883,-0.208331,0.011146,14,3,1730,drive_end,12000
122135,0.562026,-0.237300,0.008490,14,3,1730,drive_end,12000

In [11]:
DataProcessor.cepstrum_visualizer(dfs[0]['X100_FE_time'], 'FE')

In [12]:
DataProcessor.cepstrum_visualizer(dfs[1]['X188_FE_time'], 'FE_fault')

In [13]:
DataProcessor.cepstrum_visualizer(dfs[0]['X100_DE_time'], 'DE')

In [14]:
DataProcessor.cepstrum_visualizer(dfs[1]['X188_DE_time'], 'DE_fault')

In [19]:
diagnostic_df = pd.read_csv('data/data_to_check.csv')

In [20]:
diagnostic_df

              DE        FE
0       0.100761  0.011711
1       0.090956  0.129436
2       0.077605  0.022600
3      -0.009388  0.034311
4      -0.071138  0.080949
...          ...       ...
606622 -0.107646 -0.011916
606623  0.009179  0.118342
606624  0.048607  0.036776
606625 -0.190861  0.226010
606626 -0.035882  0.189635

[606627 rows x 2 columns]